### ISSUE TITLE
The instructions don't yield a binary

### ISSUE THREAD

**Issue by bbaassssiiee** [patrickmn/osg#8]
go get github.com/pmylund/osg
package github.com/golang/net/html: code in directory /Users/me/work/src/github.com/golang/net/html expects import "golang.org/x/net/html"

**Comment by ajmas** [comment]
Running into same issue, on macOS 10.12.3. Using go version 1.8 (darwin/amd64). Any ideas?

**Comment by ajmas** [comment]
Code is older than I realised and looking at one of the forks we need to change one of the imports, so it reads:

```import (
	"compress/gzip"
	"encoding/xml"
	"flag"
	"fmt"
	"golang.org/x/net/html"
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
	"strings"
	"sync"
	"time"
)
```

Essentially replace "github.com/golang/net/html" with "golang.org/x/net/html".

**Comment by patrickmn** [comment]
https://github.com/patrickmn/osg/pull/7
