### ISSUE TITLE
does it make sense to put some sleep's somewhere to make it not kill my webserver

### ISSUE THREAD

**Issue by frisbee23** [patrickmn/osg#9]
hi,
maybe you'd say it kills my apache because its "overbooked" having configured more workers, than if they all actually have to work at the same time, they allocate too much memory. you'd be right, but i think this overbooking is quite common and has its advantages.

so, i put a sleep for 500 ms onto line  157, into the crawl function, right before the recursion. i admit that i really dont exactly know what im doing, but maybe someone who understands all of the code and strange waitgroup parallel syncy stuff that seems to be going on there, might think of a smart way to only put a light load on a webserver with osg.

and yes, i used -c1, which is default.

cheers,
fil

**Comment by patrickmn** [comment]
IMO if your webserver can't handle continuous, sequential requests, that's the problem. Apache should be configured so it doesn't run out of memory.
